# -*- coding: utf-8 -*-
"""streamlit_app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PD1m5bBqJlEdqZdu8mn2zktoAuJ8JCV2
"""

import streamlit as st
from transformers import pipeline

st.title("Article Generator Chatbot")

model_option = st.selectbox("Choose a model", ["GPT-2", "GPT-Neo", "GPT-J"])

prompt = st.text_input("Enter a topic for the article")

if st.button("Generate Article"):
    with st.spinner("Generating..."):
        if model_option == "GPT-2":
            generator = pipeline('text-generation', model='gpt2')
        elif model_option == "GPT-Neo":
            generator = pipeline('text-generation', model='EleutherAI/gpt-neo-1.3B')
        elif model_option == "GPT-J":
            generator = pipeline('text-generation', model='EleutherAI/gpt-j-6B')

        result = generator(prompt, max_length=300, num_return_sequences=1)
        st.subheader("Generated Article")
        st.write(result[0]['generated_text'])

